name: Build Windows x64 EXE

# push 到 main 分支就跑
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 为后面发布做准备，保留全部历史
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller & deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build EXE with icon
        run: |
          pyinstaller --onefile --windowed --icon=myapp.ico asset_gui.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: asset_gui-windows-x64
          path: dist/asset_gui.exe
