name: Build & Release Windows EXE on tag

# 只有新打 tag 才跑
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  # 给 GITHUB_TOKEN 发布 Release 的权限
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller & deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build EXE with icon
        run: |
          pyinstaller --onefile --windowed --icon=myapp.ico asset_gui.py

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}               # e.g. v1.0.0
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/asset_gui.exe
          asset_name: asset_gui-windows-x64.exe
          asset_content_type: application/octet-stream
